### ISSUE TITLE
Timing for 0.13 release?

### ISSUE THREAD

**Issue by jonathansick** [astropy/sphinx-automodapi#114]
Hey folks, I was wondering if there are any thoughts on making a new release to PyPI (0.13?) in the near term? At Rubin Observatory we're looking to upgrade to Sphinx 3.2 for our Pipelines doc builds, and I found that the `master` branch of sphinx-automodapi is required otherwise I get a `refexplicit` exception with version 0.12 (seems to have been solved by https://github.com/astropy/sphinx-automodapi/pull/100). So just having that functionality on PyPI/conda-forge would be super helpful. Thanks!

**Comment by astrofrog** [comment]
Apologies for the delay, sphinx-automodapi v0.13 is now on PyPI

**Comment by jonathansick** [comment]
That's great news! Thanks @astrofrog and co!
