### ISSUE TITLE
reference to nonexsisting document error

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/sphinx-automodapi#15]
Hi,

I can't tell if this is a bug in automodapi, or there's something wrong with our code, but everything had been working previously when we were using astropy-helpers (which we've now stripped out).

Right now we just have one python file we're trying to include in the documentation for the code base, but when we run `make html`, automodapi seems to be looking for a different filename then the file it made...

so the file I see in the api folder is titled:
stak.Hselect.rst

but we get the following warning message from Sphinx:
None:None: WARNING: toctree contains reference to nonexsisting document u'api/stak.Hselect'

I can't tell if the warning message is just leaving off the extension on purpose and actually looking for the right file, or if it's just an issue of file names being off... as far as I can tell the contents of stak.Hselect.rst look correct.  Let me know if it would be helpful to see those.

Thanks! (And apologies if this is a problem on our end)

**Comment by SaraOgaz** [comment]
quick mention, I pulled automodapi from this repo and installed last Friday, so it's pretty new, version: 0.2.dev0

**Comment by astrofrog** [comment]
@SaraOgaz - could you point me to the repository where you are trying to use this? (just so I can try and investigate further)

**Comment by SaraOgaz** [comment]
@astrofrog  Had to push my changes to my fork, here's the version of the module I've been working on:
[https://github.com/SaraOgaz/stak/tree/hselect_work](url)

**Comment by astrofrog** [comment]
@SaraOgaz - I see the issue, though I'm puzzled how this could have worked before with astropy-helpers. The issue is because the docs are inside a ``source`` folder and it looks like the plugin doesn't deal well with that kind of situation. It's only a few lines to fix, and will try and do it by tomorrow.

**Comment by SaraOgaz** [comment]
@astrofrog  Thanks!  Looks like we moved that at the same time we stripped out astropy-helpers, so that would explain why it was working before.  Does it make sense to add that case into automodapi? We could also try and move it back out of /source...

**Comment by astrofrog** [comment]
@SaraOgaz - it should be easy to fix, will get to it today, so no need to move the docs back out of source.

**Comment by pllim** [comment]
@SaraOgaz , the easiest workaround for now is to rename `source` to `stak`.

**Comment by astrofrog** [comment]
Actually I think in this case you'd have to move the source files out of source and back to the root level to really get rid of the warnings. Sorry for the delay in getting a fix in, I ran into some Sphinx issues. I should be able to figure out a workaround today.

**Comment by astrofrog** [comment]
@SaraOgaz - I pushed a fix in https://github.com/astropy/sphinx-automodapi/pull/16 - could you test it out? Note that you'll also need to add:

```
numpydoc_class_members_toctree = False
```

to ``conf.py`` to avoid some further warnings (not quite sure why, but it all works fine then).

**Comment by astrofrog** [comment]
#16 has now been merged, so I think this issue should be fixed

@SaraOgaz - can you confirm?

**Comment by SaraOgaz** [comment]
@astrofrog, I'll try and do that today, will let you know :)

**Comment by SaraOgaz** [comment]
Success! Thanks so much @astrofrog!

**Comment by astrofrog** [comment]
@SaraOgaz - note that I've now released v0.2 so you no longer need to use the latest developer version.
