### ISSUE TITLE
Incompatibility with sphinx 6.2+ (alabaster.css_t deprecation warning)

### ISSUE THREAD

**Issue by bsipocz** [astropy/sphinx-automodapi#164]
Recent CI failures highlight some incoming incompatibility with the new sphinx version 6.2, see the failing sphinxdev jobs on `main`'s CI.

**Comment by pllim** [comment]
Thanks for reporting this! I opened https://github.com/sphinx-doc/alabaster/pull/204 upstream 🤞

**Comment by pllim** [comment]
In the meantime, I committed 5e09fd5397434d41df06970a5b1f0699a49a44c2 to ignore this warning for now.

**Comment by bsipocz** [comment]
Given this is all upstream, I'm closing the issue.
