### ISSUE TITLE
BUG: Incompatibility with sphinx-dev

### ISSUE THREAD

**Issue by bsipocz** [astropy/sphinx-automodapi#173]
At some point this became incompatible with sphinx-dev.

Also, now quite a few versions between 6.1 and sphinx-dev are not included in the text matrix, so it would be nice to add those, too.

**Comment by pllim** [comment]
I think @ayshih took care of this in #172

**Comment by bsipocz** [comment]
Do add the new versions to the matrix, too, please.

**Comment by ayshih** [comment]
Yeah, the bug is fixed by 62ba0ae

Regarding the test matrix, I'll point out that the builds intended to test against Sphinx 2.4 and 3.5 don't actually manage to install those versions, presumably because `setup.cfg` specifies Sphinx>=4.  Those builds should be removed.

**Comment by ayshih** [comment]
> Yeah, the bug is fixed by [62ba0ae](https://github.com/astropy/sphinx-automodapi/commit/62ba0ae0f6111f4ff8563bc34bcf134c48fbe887)

Hmm, although one bug was fixed, there's something else that's still a problem (seemingly in `pydata-sphinx-theme`) with the latest Sphinx.

**Comment by ayshih** [comment]
Ah, a PR merged today (sphinx-doc/sphinx#11565) renamed a method called by `pydata-sphinx-theme` from public to private.

**Comment by pllim** [comment]
Oh no... 😱

**Comment by pllim** [comment]
I have alerted pydata-sphinx-theme on their Discord but not sure what else we can do here. Either sphinx-dev reverts the breaking change or the theme has to adapt. 😢

**Comment by ayshih** [comment]
Heh, I created pydata/pydata-sphinx-theme#1404

**Comment by pllim** [comment]
Maybe it is also time to drop Python 3.7?

**Comment by bsipocz** [comment]
This compatibility issue is now addressed, and separate issues have been opened about the other things that came up during the discussion. Thanks @ayshih for the fix.
