### ISSUE TITLE
Add instructions?

### ISSUE THREAD

**Issue by pllim** [astropy/sphinx-automodapi#2]
Maybe add short instruction on README on how to include this in `conf.py`?

**Comment by astrofrog** [comment]
See http://sphinx-automodapi.readthedocs.io/en/latest/ but we aren't yet 100% sure if we are going ahead with this standalone package, so I wouldn't depend on it yet.

**Comment by pllim** [comment]
Ah, okay. Couldn't find link to that doc from GitHub page. Thanks. I'll wait but I think this will get a lot of use from STScI with packages that do not rely on Astropy but would like that Sphinx convenience.
