### ISSUE TITLE
UnicodeDecodeError on Windows when building Astropy doc

### ISSUE THREAD

**Issue by pllim** [astropy/sphinx-automodapi#28]
Windows 7, Anaconda, Python 3.5.3, Astropy 2.0.dev19112, Sphinx 1.5.6

![image](https://user-images.githubusercontent.com/2090236/27296097-7d203804-54ed-11e7-8b5c-4656bca01a37.png)

**Comment by astrofrog** [comment]
Fixed in #33 😃
