### ISSUE TITLE
Revise travis matrix

### ISSUE THREAD

**Issue by bsipocz** [astropy/sphinx-automodapi#32]
@astrofrog - is it necessary to test all the combinations on OSX, too? The additional build time is not that long, but the overhead due to the saturated OSX queue can be quite significant.

**Comment by astrofrog** [comment]
Feel free to simplify it, but this is a low-activity repo, and there is typically only one build a week, so not sure if this really makes a difference?

**Comment by bsipocz** [comment]
Hmm, you're right, this was just triggered by the relatively large traffic of yesterday :)

**Comment by astrofrog** [comment]
Things are running pretty smoothly now, and builds are actually very rare, so closing this
