### ISSUE TITLE
Docs navigation

### ISSUE THREAD

**Issue by cdeil** [astropy/sphinx-automodapi#34]
I'm learning about `sphinx-automodapi` and am trying to improve the config for the Gammapy docs.

One issue I found was that it's a bit hard to navigate the docs and back to the code on Github.

Specifically, I think adding a link back to Github from this page would be good:
http://sphinx-automodapi.readthedocs.io/en/latest/

Then from sub-pages like
http://sphinx-automodapi.readthedocs.io/en/latest/automodapi.html
there's no navigation element to go back to the top-level docs page!?

Finally, it can be nice to have next / previous buttons on pages, for people like me that would like to scan the docs once from start to end.

OK to make these changes? Or do you have a preference for how it is now?

**Comment by astrofrog** [comment]
I think some of these things must be theme dependent, and might also indicate that I'm not using the right heading characters (i.e. we shouldn't have to edit the theme or add explicit links for many of these). Feel free to take a look at this and maybe you can try for instance the sphinx-rtd-theme. If you can't get it all to work, just let me know and I'll take a look.

I agree about adding a link to GitHub

**Comment by astrofrog** [comment]
I switched to sphinx-rtd-theme in a0a62cbd5a927b6a455fce8e9e58491f87381a6c which makes it easy to go to the top level and also has previous/next buttons
