### ISSUE TITLE
autosummary causes bad linking on Windows

### ISSUE THREAD

**Issue by pllim** [astropy/sphinx-automodapi#41]
I attempted to build docs for `astropy` v3.1dev on Windows and got over 3000 warnings like this:
```
<autosummary>:: WARNING: toctree contains reference to nonexisting document 'wcs/..\\api/astropy.wcs.utils.custom_frame_to_wcs_mappings'
```
Not just `wcs` is affected, which led me to believe that the bug is upstream over here.

**Comment by astrofrog** [comment]
Looks like a mix of / and \ - we do run tests on AppVeyor here but it's possible there are some corner cases that don't work right on Windows.

**Comment by pllim** [comment]
Update: Still an issue with `3.2.dev23734`
```
build succeeded, 4284 warnings.
```

**Comment by astrofrog** [comment]
I think what we need to do is come up with a minimal example and include it in the CI here. Do you see this on simpler packages than astropy?

**Comment by astrofrog** [comment]
I think it's actually a simple problem - testing a hypothesis in https://github.com/astropy/sphinx-automodapi/pull/63

**Comment by astrofrog** [comment]
This is fixed by https://github.com/astropy/sphinx-automodapi/pull/63 - there are still some warnings in the astropy docs build (mainly related to references) but that's unrelated.

**Comment by astrofrog** [comment]
@pllim - I think I know how to solve the remaining warnings. More soon.

**Comment by astrofrog** [comment]
@pllim - I've now fixed most of the remaining warnings. Can you confirm that there are no more warnings with the latest developer version of sphinx-automodapi?

**Comment by pllim** [comment]
I'll report back when I get a chance. Thank you so much!

**Comment by pllim** [comment]
I can confirm that with the patch in `master`, I only get 10 warnings now and they are nothing new (Matplotlib FutureWarning and such). Thank you!
