### ISSUE TITLE
Sphinx class inheritance diagrams not linking classes correctly

### ISSUE THREAD

**Issue by hamogu** [astropy/sphinx-automodapi#48]
E.g. at https://astropy.readthedocs.io/en/latest/visualization/index.html#module-astropy.visualization

click on any class in the graph-viz Diagram - None of them work, because there is a "/latest/" missing in the url. I'm reporting this here, but I'm not entirely sure if this is a sphinx-automodapi issue or related to some configuration in astropy itself.

**Comment by nritsche** [comment]
https://dias.readthedocs.io/en/rn-docs/dev/reference.html

The diagram links point to a different `.rst` than the class name links.

**Comment by bsipocz** [comment]
I've run into the broken links again, today.

It's useful to link to these following issues as PRs and most of the relevant discussions happened on them:

 https://github.com/astropy/astropy/issues/4935

and upstream fixes and more discussions on how it should be fixed instead here, in this extension:
https://github.com/sphinx-doc/sphinx/pull/2484
https://github.com/sphinx-doc/sphinx/pull/6454

**Comment by ayshih** [comment]
This is actually a bug in Sphinx after all.  See sphinx-doc/sphinx#10576

**Comment by pllim** [comment]
Thanks for investigating and opening upstream fix!

**Comment by pllim** [comment]
I think this is fixed by #172
