### ISSUE TITLE
API documentation appears in api/ and not docs/api/ when using python setup.py build_sphinx

### ISSUE THREAD

**Issue by DougBurke** [astropy/sphinx-automodapi#58]
I am trying to use astropy_helpers in generating some documentation for http://github.com/sherpa/sherpa/ and have come across the following puzzler (which may be some stupid mistake on my part, or a bizarre interaction with various pieces of the documentation stack I am using, or ...). When I use `python setup.py build_sphinx`, the api documentation is written to `api/`, rather than `docs/api/`, which then causes all sorts of warnings about missing content and references (and the ever-so-slightly serious issue of the API documentation not appearing in the HTML output). You can see the fun start at
https://travis-ci.org/sherpa/sherpa/jobs/131963375#L4116

I've tried to dig into the problem, and I can get the API to be placed in `docs/api/` by tweaking `astropy_helpers/sphinx/ext/automodsumm.py`, by changing https://github.com/astropy/astropy-helpers/blob/4b01f93eb164b66569691d79842e72ad2ccdded7/astropy_helpers/sphinx/ext/automodsumm.py#L458

from

```
    path = os.path.abspath(path)
```

to

```
    path = os.path.join(base_path, path)
    path = os.path.abspath(path)
```

I do not know whether this is a sensible thing to do. It also does not completely fix things for me: at this point the API is correct but the links in the graphviz-generated inheritance displays are wrong (there's either a missing `html/` in the path or an extra `../` somewhere; I assume it's related to the same issue but I wanted to understand this part first).

I did start off with the easy things - e.g. changing the value of the `automodapi_toctreedirnm` configuration variable - but that didn't work, which eventually lead me to digging into the astropy_helpers code base.

The screen output of a `python setup.py build_sphinx` run, which contains lots of warnings about missing documents because the api files aren't being written to `docs/api/`) can be found at https://travis-ci.org/sherpa/sherpa/jobs/131963375

The code can be found at the feature/sphinx-docs branch - i.e. https://github.com/sherpa/sherpa/tree/feature/sphinx-docs and there is a section in the README.md showing how to build the documentation (if this problem is "intriguing enough" to get to the point of trying to replicate my experience).

Possibly relevant version info (I expliclty use IPython < 4.1 because of https://github.com/ipython/ipython/issues/8733):

```
% conda list sphinx
# packages in environment at /home/djburke/miniconda2/envs/sherpa-sphinx:
#
sherpa (/home/djburke/sherpa/sherpa-sphinx) 4.8.1+87.gd11e359           <pip>
sphinx                    1.4.1                    py27_0  
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0  
% conda list ipython
# packages in environment at /home/djburke/miniconda2/envs/sherpa-sphinx:
#
ipython                   4.0.3                    py27_0  
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0  
```

Let me know if you need any further information.

**Comment by astrofrog** [comment]
This was fixed in astropy-helpers in https://github.com/astropy/astropy-helpers/pull/428
