### ISSUE TITLE
Disable inheritance diagrams by default?

### ISSUE THREAD

**Issue by astrofrog** [astropy/sphinx-automodapi#6]
If this is to be used beyond Astropy, and given that graphviz is not always installed, I wonder if it would make sense to make the inheritance diagrams opt-in?

**Comment by astrofrog** [comment]
@cdeil - I'm not sure if many people have weighed in on this, but if you have a few minutes, could you open a PR and then just email astropy-dev to see if there are any objections?

**Comment by astrofrog** [comment]
By the way we could make this a global option so people can turn it back on easily?

**Comment by cdeil** [comment]
I agree this would be good to have as a global option. In Gammapy, I have `:no-inheritance-diagram:` on all ~ 20 `automodapi` directives.

Probably best to do the addition of the global options first, and then the change of the default separately later. If it requires mailing list discussion it'll take some time or might be shot down to not rock the boat. (and if there's a global option, it's a one-line `conf.py` edit, so the motivation to change the default is smaller).

**Comment by astrofrog** [comment]
@cdeil - ok sounds good, do you want to work on adding the global option?

**Comment by pllim** [comment]
Changing default now would make people cry. I think that ship has sailed.
