### ISSUE TITLE
Can this package be added to conda-forge?

### ISSUE THREAD

**Issue by waderoberts123** [astropy/sphinx-automodapi#70]
I am a fan of conda as a package manager, and sphinx is included in conda-forge. Could this package be added to conda-forge?

Looking through the code, it doesn't seem to use any dependencies that aren't already included in conda-forge, so it seems as though it would be easy to submit a PR to their github page and package it as a NOARCH package.

**Comment by bsipocz** [comment]
This is already on `conda-forge`. The package then (along with the rest of the astropy ecosystem) is also available on the astropy conda channel.

https://github.com/conda-forge/sphinx-automodapi-feedstock
