### ISSUE TITLE
Conda version is out of date

### ISSUE THREAD

**Issue by ehsteve** [astropy/sphinx-automodapi#89]
It looks like the latest Conda release for this package is 0.11. Unfortunately that version is out of date with Sphinx and leads to the following error when trying to build docs
```
File "/Users/sdchris1/anaconda3/lib/python3.7/site-packages/sphinx_automodapi/automodapi.py", line 285, in automodapi_replace
    app.warn(msg, location)
AttributeError: 'Sphinx' object has no attribute 'warn'
```
This has been fixed in 0.12 so if the Conda release was updated then this would go away. I supposed this also means that the dependency list could be updated to make sure that 0.11 runs an earlier version of sphinx.

This may be also true of the pipy release as well though I have not checked.

**Comment by astrofrog** [comment]
I've now merged https://github.com/conda-forge/sphinx-automodapi-feedstock/pull/5 so this should now be fixed.
