### ISSUE TITLE
Is it possible to specify classes for automodapi

### ISSUE THREAD

**Issue by appukuttan-shailesh** [astropy/sphinx-automodapi#92]
I like the use of `automodapi`, but was curious if there is a way to specify the classes that should be displayed. Basically the opposite of `:skip: str` (which allows us to remove unnecessary entries).

Is there any option to specify what we want included? I see that this is possible via autosummary (it's default behavior), but given a choice, I would like to use automodapi because of other benefits.

As a hack currently I am having to create a large exclusion list to supply to `:skip:`. But this isn't neat, as I often need to document only 5-6 classes, while having to exclude a much larger number of entries.

**Comment by adrn** [comment]
See #127, now merged into main!

**Comment by adrn** [comment]
(ps: @saimn this can be closed)

**Comment by appukuttan-shailesh** [comment]
Thanks @adrn for implementing this!
